INSERT OR REPLACE INTO published_articles (
  slug, title, excerpt, body, channel, tags_json, sources_json, author, published_at, image_url
) VALUES (
  'menjelajah-kekayaan-kuliner-khas-kediri-tahu-takwa-nasi-goreng-arang',
  'Menjelajah Kekayaan Kuliner Khas Kediri: Dari Tahu Takwa Hingga Nasi Goreng Arang',
  'Ulasan mendalam seputar keunikan dan sejarah kuliner khas Kediri Raya, mulai dari Tahu Takwa, Gethuk Pisang, hingga Nasi Goreng Arang yang legendaris.',
  '["Kediri tidak hanya dikenal sebagai salah satu pusat pertumbuhan ekonomi Jawa Timur, tetapi juga menyimpan ragam kekayaan kuliner tradisional yang sarat sejarah dan cita rasa khas.","Bagi wisatawan maupun pecinta wisata boga, menjelajahi ragam makanan khas Kediri memberikan pengalaman tersendiri. Mulai dari camilan legendaris bertekstur khas hingga hidangan malam yang dimasak secara tradisional dengan tungku arang.","### 1. Tahu Takwa: Ikon Kuliner Legendaris Kediri","Tahu Takwa merupakan ikon paling tersohor dari Kota Kediri. Memiliki warna kuning alami yang didapat dari pewarna kunyit, Tahu Takwa dikenal dengan teksturnya yang padat, lembut di dalam, dan gurih renyah saat digoreng.","Tradisi pembuatan Tahu Takwa telah berlangsung sejak awal abad ke-20 dan kini dikembangkan oleh puluhan UMKM kuliner lokal Kediri. Tahu Takwa tidak hanya lezat disajikan hangat bersama cabai rawit, tetapi juga menjadi buah tangan wajib bagi siapapun yang berkunjung ke Kediri.","### 2. Gethuk Pisang: Manis Legit Beraroma Khas","Berbeda dengan gethuk pada umumnya yang berbahan dasar singkong, Gethuk Pisang khas Kediri dibuat dari pisang raja nangka pilihan. Pisang ini memiliki keseimbangan rasa manis dan sedikit asam yang pas ketika diolah.","Dibungkus rapi menggunakan daun pisang berbentuk silinder memanjang, Gethuk Pisang memiliki tekstur kenyal dan aroma harum alami. Camilan ini bebas dari bahan pengawet sintesis sehingga sangat disukai sebagai oleh-oleh khas keluarga.","### 3. Nasi Goreng Arang: Sensasi Asap Tradisional yang Menggugah Selera","Saat malam tiba, sudut-sudut kota Kediri dihiasi oleh deretan penjual Nasi Goreng Arang (sering disebut Nasi Goreng Kediri). Ciri khas utamanya adalah proses memasak yang tetap setia menggunakan anglo (tungku tanah liat) dan arang kayu.","Penggunaan arang menghasilkan *smokey flavor* (aroma asap gurih) yang khas pada setiap bulir beras. Disajikan dengan suwiran ayam kampung, telur, dan acar segar, hidangan ini menjadi favorit lintas generasi.","### Peluang Bisnis UMKM Kuliner Nusantara","Pertumbuhan bisnis kuliner lokal di Kediri membuktikan bahwa warisan resep tradisional mampu bersaing dan bertransformasi di era digital. Dengan sentuhan kemasan modern dan pemasaran digital, kuliner daerah kini berpotensi menembus pasar nasional."]',
  'kuliner',
  '["Kuliner","Kediri","Tahu Takwa","Resep Nusantara","UMKM Kuliner"]',
  '[{"title":"Kemenparekraf RI - Potensi Kuliner Nusantara","url":"https://www.kemenparekraf.go.id/"}]',
  'Redaksi AnekaNews',
  '2026-08-05 18:00:00',
  '/images/tda-kediri-cangkrukan-bisnis-umkm.webp'
);